### PR TITLE
Fix shulker boxes not working properly

### PR DESCRIPTION
**Pull request by TheLimeGlass**
All shulker boxes did not work before this pull, aswell as certain comparisons.

### CODE REVIEW

**Review by APickledWalrus — COMMENTED** [review]
Doesn't this conflict on newer versions though?
`{orientable} [normal] shulker box¦es = minecraft:shulker_box` and `[any] shulker box¦es` both share `shulker box`

**Comment by TheLimeGlass** [comment]
> Doesn't this conflict on newer versions though? `{orientable} [normal] shulker box¦es = minecraft:shulker_box` and `[any] shulker box¦es` both share `shulker box`

No because it has `{orientable}`
```
normal shulker box = that purple undyed box
down facing shulker box = same as above just in a direction
any shulker box = any coloured shulker box including the uncoloured one
all shulker boxes = all shulker boxes and the uncoloured one, no duplicates
```
Only issue that already exists before this fix is that an orientable shulker box is always the uncoloured one unless you define a colour like `down facing lime shulker box` I don't know how something like `{orientable} shulker box¦es = any shulker box` is supposed to work, so I didn't touch that, it's fine as it is now I guess where they must define the colour.

`down facing shulker box` should be taking from `any shulker box` in my opinion.

**Comment by APickledWalrus** [comment]
This will conflict because a shulker box is not necessarily colored. It may have `{orientable}`, but it's optional (e.g. it can be "blank"), thus `shulker box` is already an existing alias to get a plain sulker box.

**Comment by TheLimeGlass** [comment]
But a normal shulker box is still a shulker box, should [normal] not be optional then?

**Comment by APickledWalrus** [comment]
Hmm yeah with the current state of the system it might be best to make `any` optional and make `normal` required. Maybe we could have like `(normal|uncolored)`? Up to you

We will want to record this as a breaking change though.

**Pull request merged**
