### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by HYPExMon5ter**
Added the development skript version that you can use to test the new aliases out on to the readme.

### CODE REVIEW

**Comment by Blueyescat** [comment]
Doesn't link to the latest release always.

**Comment by TheBentoBox** [comment]
Yeah, it should probably just link to the general releases page of the repo ([here](https://github.com/SkriptLang/skript-aliases/releases/)).

**Comment by HYPExMon5ter** [comment]
I’ll fix

**Comment by Blueyescat** [comment]
*Sending a message to bensku on Discord was easier.*

**Comment by HYPExMon5ter** [comment]
I did lol, he still hadn't updated it though so I figured I'd make a PR

**Comment by TheBentoBox** [comment]
No reason not to merge this now that I can. Thanks for the contribution!

**Pull request merged**
