### PR TITLE
Horse armor update / Foodstuff update

### PR DESCRIPTION
**Pull request by ShaneBeee**
#### Combat 
When I did the horse armor and barding, I feel I did it wrong.
I put  "iron horse armor or iron horse barding" when it should have been "iron horse armor or iron barding"
Example (should be):
```iron (horse armo[u]r|barding)```
instead of (what I first put):
```iron horse (armo[u]r|barding)```
Tiny change, but more grammatically correct plus matches the actual minecraft ID's better
"iron_barding" and "iron_horse_armor"

#### FoodStuffs
- Fixed a spelling mistake in and potato (was spelled poato)
- Added brackets to raw chicken and rabbit to keep consistency with other raw foods
- Changed all spaces to tabs to keep consistency with other alias files, (Saw a comment from Bensku on another pull request that he prefers tabs)

### CODE REVIEW

**Comment by ShaneBeee** [comment]
ho
Lord... That's embarrassing... Fixing spelling mistakes and I cant even spell "Spelling mistake" properly .... How about we all just look past that ;) or pretend it's German?!?

**Comment by TheBentoBox** [comment]
I think this makes enough sense. Thanks for the fixes!

**Comment by Blueyescat** [comment]
Shouldn't this be changed too?
```
[any] horse armo[u]r = iron horse armor, gold horse armor, diamond horse armor
```

[any] horse (armo[u]r|barding)

**Comment by ShaneBeee** [comment]
You are very correct, should I quickly do another PR for that?
Edit: Did another PR for it!

**Pull request merged**
