### PR TITLE
Updated boats

### PR DESCRIPTION
**Pull request by ShaneBeee**
Boat id's in 1.12.2 or older were like so:
boat_acacia

New boats:
acacia_boat

### CODE REVIEW

**Comment by Blueyescat** [comment]
Nope, it is x_boat in 1.12.2.

**Comment by TheBentoBox** [comment]
I'm not finding this to be true, at least on 1.12.2:

image

**Comment by TheBentoBox** [comment]
Yeah, I just checked 1.9 (which is when these boats were added) and this isn't the case either:
image

Think you just made a mistake when viewing something, so I'll be closing.

**Comment by ShaneBeee** [comment]
Ah... well then the 1.12.2 Spigot docs LIED to me.... damn them ;)
Sorry guys

**Pull request closed without merging**
